export declare const isArray: (maybe: any) => boolean;
export declare const mustBeNumber: (maybe: any) => number;
export declare const mustBeString: (maybe: any) => string;
export declare const mustBeBoolean: (maybe: any) => boolean;
export declare const is: (pType: string) => (maybe: any) => boolean;
export declare const mustBe: <T>(pType: string) => (maybe: any) => T;
export declare const mustBeArrayOf: <Atype>(aType: string) => (maybe: any) => Atype[];
export declare const mustBeArrayOfNumbers: (maybe: any) => number[];
export declare const mustBeArrayOfStrings: (maybe: any) => string[];
export declare const mustBeArrayOfBooleans: (maybe: any) => boolean[];
